---
- name: Include Lesson Playbook
  hosts: all
  become: yes

  vars:
    text: "Hello from Suetolog"

  tasks:
  - name: Ping test
    ping:


  - name: Create Folders
    include: create_folders.yml

  - name: Create Files
    include: create_files.yml